version: 1.0.{build}

environment:
  rsa_key_secret:
    secure: 70j87wGCHbd0LVwMJIemhFSJPW3iuEcXiUC1kUsnm0p2KyofSwHn3mi74yALaAYw

install:
  - nuget install secure-file -ExcludeVersion
  - cinst winscp

  - set root_dir=%cd%
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat amd64
  - set PATH=%PATH%;C:\"Program Files (x86)"\7-zip


  - REM ---------------------------------
  - REM GLEW
  - REM ---------------------------------

  - SET glew_url="https://netcologne.dl.sourceforge.net/project/glew/glew/2.0.0/glew-2.0.0.zip"
  - SET glew_zip="%root_dir%\third_party\glew-2.0.0.zip"
  - SET glew_dir="%root_dir%\third_party\glew-2.0.0"

  - echo "Downloading %glew_url%"
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('%glew_url%', '%glew_zip%')"
  - echo "Extracting %glew_zip%"
  - 7z x -o"%root_dir%/third_party" "%glew_zip%"

  - SET glew_install_prefix="%root_dir%/third_party/glew-bin"
  - cd %glew_dir%
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%glew_install_prefix%" ./cmake
  - nmake
  - cmake -P cmake_install.cmake

  - cd %root_dir%


  - REM ---------------------------------
  - REM Bullet
  - REM ---------------------------------

  - SET bullet_url="https://github.com/bulletphysics/bullet3/archive/2.86.1.zip"
  - SET bullet_zip="%root_dir%\third_party\bullet-2.86.1.zip"
  - SET bullet_dir="%root_dir%\third_party\bullet3-2.86.1"

  - echo "Downloading %bullet_url%"
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('%bullet_url%', '%bullet_zip%')"
  - echo "Extracting %bullet_zip%"
  - 7z x -o"%root_dir%/third_party" "%bullet_zip%"

  - SET bullet_install_prefix="%root_dir%/third_party/bullet-bin"
  - cd %bullet_dir%
  - mkdir build
  - cd build

  - cmake -G "NMake Makefiles" -DBUILD_BULLET2_DEMOS=OFF -DBUILD_BULLET3=OFF -DBUILD_CPU_DEMOS=OFF -DBUILD_EXTRAS=OFF -DBUILD_OPENGL3_DEMOS=OFF -DBUILD_UNIT_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DINSTALL_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%bullet_install_prefix%" ..
  - nmake
  - cmake -P cmake_install.cmake


  - REM ---------------------------------
  - REM SWIG
  - REM ---------------------------------

  - SET swig_url="https://netix.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.12/swigwin-3.0.12.zip"
  - SET swig_zip="%root_dir%\third_party\swigwin-3.0.12.zip"
  - SET swig_dir="%root_dir%\third_party\swigwin-3.0.12"

  - echo "Downloading %swig_url%"
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('%swig_url%', '%swig_zip%')"
  - echo "Extracting %swig_zip%"
  - 7z x -o"%root_dir%/third_party" "%swig_zip%"


  - cd %root_dir%

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles"
      -DCMAKE_BUILD_TYPE=Release
      -DTOWERENGINE_ENABLE_COTIRE=OFF
      -DCMAKE_PREFIX_PATH="%glew_install_prefix%;%bullet_install_prefix%"
      -DPYTHON_LIBRARY=C:/Python35-x64/libs/python35.lib
      -DPYTHON_INCLUDE_DIR=C:/Python35-x64/include
      -DTOWERENGINE_BUILD_DEVIL=OFF
      -DTOWERENGINE_BUILD_LIBPNG=OFF
      -DTOWERENGINE_BUILD_STATIC=ON
      -DTOWERENGINE_SWIG_PYTHON=ON
      -DTOWERENGINE_BLENDER_ADDON=ON
      -DSWIG_DIR="%swig_dir%"
      -DSWIG_EXECUTABLE="%swig_dir%\swig.exe"
      -DTOWERENGINE_BLENDER_ADDON_PACK_ADDITIONAL_FILES="%glew_install_prefix%\bin\glew32.dll"
      ..
  - nmake
  - nmake blender-addon
  - cd %root_dir%


deploy_script:
  - secure-file\tools\secure-file -decrypt .appveyor_rsa.ppk.enc -secret %rsa_key_secret% -out appveyor_rsa.ppk
  - C:\"Program Files (x86)"\WinSCP\WinSCP.com /ini=nul /command
     "open sftp://ci@ci.metallic.software -privatekey=appveyor_rsa.ppk -hostkey=""ecdsa-sha2-nistp256 256 3f:da:44:3d:c5:a2:b6:72:c0:a9:06:2c:16:85:a4:9e"""
     "cd build/towerengine"
     "put build\blender\towerengine-blender.zip ./towerengine-blender-%APPVEYOR_REPO_COMMIT:~0,7%-windows-amd64.zip"
     "exit"
